# windows
  [target.x86_64-pc-windows-gnu]
  rustflags = [
    "-L", "C:/msys64/ucrt64/lib",
    "-lSDL2"
  ]

# mac
#[target.aarch64-apple-darwin]
#rustflags = [
#  "-L", "/opt/homebrew/opt/sdl2/lib",
#  "-L", "/opt/homebrew/opt/sdl2_image/lib",
#  "-L", "/opt/homebrew/opt/sdl2_ttf/lib",
#  "-lSDL2",
#  "-lSDL2_image",
#  "-lSDL2_ttf"
#]
#